version: '3.8'
services:
  reactiverates:
    build: .
    image: reactiverates:latest
    container_name: reactiverates
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=reactive_rates_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - reactiverates

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: reactive_rates_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
