server:
    port: 8080

spring:
    application:
        name: ReactiveRates API
    jackson:
        default-property-inclusion: non-null
        serialization:
            write-dates-as-timestamps: false
    
    r2dbc:
        url: r2dbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:reactive_rates_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        pool:
            enabled: true
            initial-size: 5
            max-size: 20
            max-idle-time: PT30M

    datasource:
        jdbcUrl: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:reactive_rates_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: never
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.xml
        url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:reactive_rates_db}
        user: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}

exchangerate-api:
  base-url: https://v6.exchangerate-api.com
  api-key: feedc09fac544d8041317c40
  priority: 10
  timeout: 10s
  connect-timeout: 5s

unirate-api:
    base-url: https://api.unirateapi.com
    api-key: QashoCNTEdDqrEYt2WMMvUSMo3tyJz8BHpCXkqvSSgBUbqB5ruk7lu4HvwXbp3GV
    priority: 20
    timeout: 10s
    connect-timeout: 5s

mock-provider:
  enabled: true

cache:
    enabled: true
    ttl: PT5M
    max-size: 1000

springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        display-request-duration: true
        groups-order: ASC
        operationsSorter: method
        disable-swagger-default-url: true
        doc-expansion: none
        tagsSorter: alpha
    show-actuator: false
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

logging:
    level:
        com.reactiverates: ${LOG_LEVEL:DEBUG}
        org.springframework.web: ${LOG_LEVEL:INFO}