server:
    port: 8080

spring:
    application:
        name: reactive-rates-api
    jackson:
        default-property-inclusion: non-null
        serialization:
            write-dates-as-timestamps: false

# Конфигурация провайдеров курсов валют
exchange-rate:
    mock:
        enabled: true  # Используем Mock-провайдер для разработки
    external-api:
        # Конфигурация для реального API (отключен в dev режиме)
        base-url: https://api.exchangerate.host
        timeout: 10s
        connect-timeout: 5s
        api-key: # Укажите ваш API ключ здесь для production

external-apis:
    exchange-rate:
        base-url: https://api.exchangerate.host
        timeout: 10s
        connect-timeout: 5s

# Конфигурация для SpringDoc OpenAPI (Swagger)
springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        display-request-duration: true
        groups-order: ASC
        operationsSorter: method
        disable-swagger-default-url: true
        doc-expansion: none
    show-actuator: false
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

# Логирование для отладки
logging:
    level:
        com.reactiverates: DEBUG
        org.springframework.web: DEBUG