server:
    port: 8080

spring:
    application:
        name: reactive-rates-api
    jackson:
        default-property-inclusion: non-null
        serialization:
            write-dates-as-timestamps: false

unirate-api:
    base-url: https://api.unirateapi.com
    timeout: 10s
    connect-timeout: 5s
    api-key: ${UNIRATE_API_KEY:QashoCNTEdDqrEYt2WMMvUSMo3tyJz8BHpCXkqvSSgBUbqB5ruk7lu4HvwXbp3GV}

springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        display-request-duration: true
        groups-order: ASC
        operationsSorter: method
        disable-swagger-default-url: true
        doc-expansion: none
    show-actuator: false
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

logging:
    level:
        com.reactiverates: ${LOG_LEVEL:DEBUG}
        org.springframework.web: ${LOG_LEVEL:DEBUG}